language: php

php:
  - 7.2

before_script:
  - composer install --no-interaction  
  - php artisan key:generate

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover